### ISSUE TITLE
Add historic data for 2017, 2018

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics-cruncher#14]
The historic snapshot for 1/1/2017 is missing from the timeline in the before/after tool.

Let's also document the process of creating these snapshots to make it easier to add them for other map features.

**Comment by jenningsanderson** [comment]
:wave: Hey @cgiovando I've updated the historic snapshots, the 2017-01-01 snapshot is available here: https://s3.amazonaws.com/mapbox/osm-qa-tiles/historic/2016-Q4-qa-tiles.mbtiles

See: http://osmlab.github.io/osm-qa-tiles/historic.html# for more information on these files / how they were generated. Note the move to quarterly snapshots instead of annual snapshots; for better historical resolution, these historical snapshots should be able to plug directly into the current workflow.

**Comment by tyrasd** [comment]
We also had incomplete (and in a few cases wrong) historic osm-analytics snapshot data (e.g. for waterways layers only two snapshots had been calculated that contained odd results, and at least one of the highways snapshots had been produced for the correct timestamp).

I'm now re-creating all the historic osma-snapshots using the [osm-qa-tiles quarterly historic snapshots](http://osmlab.github.io/osm-qa-tiles/historic.html#) (using the Q4 snapshot of each year) in order to fix the bad data in the current historic snapshots and to provide the missing more recent yearly snapshots for 2017 and 2018. The resulting snapshots until 2017 (inclusive) are [already online](https://github.com/hotosm/osm-analytics/commit/8ced59a77384472b431ab42b88b8168966f79492); ~~2018 is still processing but should be done in a few hours~~ //edit: [as are the 2018 snapshots](https://github.com/hotosm/osm-analytics/commit/fd98bb7d873c49bdbbdd8640f527e1a1aa457d42)

> document the process of creating these snapshots

In principle, it's just the same* as invoking the normal cruncher, but using a different osm-qa-tiles input file (i.e. one of the quarterly snapshots instead of the most recent planet osm-qa-tiles file) specified by the appropriate URL as [`OSMQATILES_SOURCE` environment variable](https://github.com/hotosm/osm-analytics-cruncher#environment-variables). (* One minor adaption is needed because the historic osm-qa-tiles snapshots are not gzip-compressed: just remove the `| gzip -d` command in `run.sh`).
