### ISSUE TITLE
Update OSM-QA-Tiles endpoint

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics-cruncher#20]
Hi @tyrasd - we've set up a new OSM-QA-Tiles processing stack and the new planet endpoint is available here `https://hot-qa-tiles.s3.us-east-2.amazonaws.com/latest.planet.mbtiles.gz`

I can update the `OSMQATILES_SOURCE` parameter in the [`run.sh file`](https://github.com/hotosm/osm-analytics-cruncher/blob/dd978f268533968ecd291a70d48e9c54d0e23bff/app/run.sh), but just wanted to check with you if there are other changes that need to be done?

Also, we're probably going to set the creation frequency to once a week. Not sure if that will impact the cruncher and the _last update_ settings.

Thanks!

cc: @ramyaragupathy @dakotabenjamin

**Comment by tyrasd** [comment]
Hi. Great news.

You are right, the `run.sh` file is the only place to change the default source for the osm-qa-tiles input data.

> Also, we're probably going to set the creation frequency to once a week.

IMO, it would make sense to also run the cruncher only once per week. I believe it should be possible to write a small script which checks wether there is a new osm-qa-tiles planet file available and only start the cruncher if there is one available.

**Comment by tyrasd** [comment]
PS: is it expected that the new _hot-qa-tiles_ `latest.planet.mbtiles.gz` is quite a bit smaller than the one published by mapbox. It seems to be just below 40GB, white the one from mapbox is larger than 80GB. :thinking:

**Comment by mikelmaron** [comment]
great news. does this potentially mean we could link https://osmlab.github.io/osm-qa-tiles/ to this new endpoint?

**Comment by tyrasd** [comment]
>> Also, we're probably going to set the creation frequency to once a week.
>
> IMO, it would make sense to also run the cruncher only once per week.

the new workflow seems to work fine: the cruncher now hourly checks for updates of the input data (via the last-modified header `curl -s --head https://hot-qa-tiles.s3.us-east-2.amazonaws.com/latest.planet.mbtiles.gz | grep Last-Modified`) and crunches the data only if there actually is fresh data available

**Comment by mikelmaron** [comment]
@cgiovando are the HOT QA Tiles now stable? Should we point  https://osmlab.github.io/osm-qa-tiles/  at them?

**Comment by dakotabenjamin** [comment]
@tyrasd i'm looking into why it's so much smaller but not sure at the moment. Please reach out if you notice anything yourself. 

@mikelmaron everything seems to be working well right now- just make sure to note it's updated weekly now.

**Comment by tyrasd** [comment]
> Please reach out if you notice anything yourself.

I noticed that the hot-qa-tiles don't seem to include multipolygon relation buildings anymore. PS: The "original" osm-qa-tiles back in the days when osm-analytics was originally build didn't include any multipolygon relations. Some time later they were added resulting in a significant bump in the planet file size and cruncher processing times.

**Comment by jenningsanderson** [comment]
@tyrasd, after talking with @dakotabenjamin today, it looks like the older script with `minjur` was implemented in this stack instead of the newer version using `osmium-export`, it's therefore not using many multi-polygons / relations ... especially not land-cover, hence it's much smaller in size.

For reference, this [osmium](https://github.com/osmlab/osm-qa-tiles/tree/osmium) branch has instructions on how to use osmium-export and the example [configuration file](https://github.com/osmlab/osm-qa-tiles/blob/osmium/osm-qa-tile.osmiumconfig) which will create the 80G version that folks are familiar with from the past 2 years. 

Additionally, see [Step 3.5](https://github.com/osmlab/osm-qa-tiles/tree/osmium#35-optional-filter-out-very-large-polygons-and-administrative-boundaries-to-create-a-compact-version-for-those-interested-in-roads-buildings-etc) in those instructions to implement a quick filter script that Tom and I were testing to filter out administrative boundaries and coastlines for a more 'compact' osm-qa-tiles file... that's closer to 40G and has a more streamlined version of what the hot-osm-cruncher is _really_ counting...

(When osmium-export does all of the relations as multipolygons, the southern 1/4 of the globe is entirely included with single polygon features per tile that denote Antarctica land ownership (administrative boundaries)... this means these files have ~10M tiles as opposed to a compact version (w/o administrative boundaries) which has < 5M tiles).  That's the size difference.

While it'll be a major performance improvement to move to `osmium-export`, and all _other_ users of osm-qa-tiles are likely expecting the 80G file... the capabilities of `minjur` to handle roads, buildings, and points-of-interest is fine for now, so the hot-analytics-cruncher is not seeing much difference in the dataset that it's quantifying. 

EDIT: After some further inspection of what's being shown on osm-anlaytics.org today vs. what's in OSM, there might be a significant amount of data missing?

**Comment by tyrasd** [comment]
Thanks for the clarification

> After some further inspection of what's being shown on osm-analytics.org today vs. what's in OSM, there might be a significant amount of data missing?

For the roads, rivers and places layers there shouldn't be any differences because of missing relations.
For buildings the missing number should be relatively small, since only a very small percentage of buildings are mapped as multipolygons: https://taginfo.openstreetmap.org/keys/building
The amenities and particularly the hospitals layer would be affected the most, since a few percent of them are mapped as multipolygon relations: https://taginfo.openstreetmap.org/tags/amenity=hospital

On a side note, it seems like the limitations listed on https://github.com/hotosm/osm-analytics/blob/master/documentation/architecture.md#limitations never got updated. So the section about missing multipolygons is now correct again. :sweat_smile:

**Comment by tyrasd** [comment]
> After some further inspection of what's being shown on osm-analytics.org today vs. what's in OSM, there might be a significant amount of data missing?

:thinking: Hmm, I took a second look at the data now, and it does indeed seem that there is quite a bit more data missing in the hot-qa-tiles than can be explained by the missing multipolygon relations. For example I'm not able to find https://www.openstreetmap.org/way/753186483 in the data processed by the osm-analytics-cruncher these days. Could it be that the hot-qa-tiles are not generated from an up-to-date and complete OSM planet file? At first glance it seems that mostly regions show discrepancies where buildings have been mapped in the few months or so. Another example where data seems to be missing from the hot-qa-tiles data set is https://www.openstreetmap.org/#map=16/-7.7611/15.2593 while regions mapped earlier seem to produce correct results (Kathmandu, for example). Very odd.

**Comment by jenningsanderson** [comment]
I see the same thing when spot-checking the map for buildings. Cairo, Egypt, for example, has about 50% of the buildings that OSM shows. 

I think the root of these problems are all with using `minjur` and I think the hot-qa-tiles stack should be updated to `osmium-export` [Full instructions here](https://github.com/osmlab/osm-qa-tiles/tree/osmium).  For comparison, I will run a full-planet osm-qa-tiles with `osmium export` and make it available here for a side-by-side comparison.

@tyrasd, I saw your comment on [this change](https://github.com/hotosm/osm-analytics-cruncher/commit/d8b30c96b45828850b77a2d430ba9394476ef248), which makes me _very_ curious. This makes me think that the `minjur` version currently being used is older because `minjur` should default to `@` as the prefix?

Again, these are all very solvable by updating to `osmium-export`, happy to help however I can.

**Comment by tyrasd** [comment]
> I saw your comment on this change, which makes me very curious. This makes me think that the minjur version currently being used is older because minjur should default to @ as the prefix?

To be honest, I just noticed (while investigating issue https://github.com/hotosm/osm-analytics/issues/103) that the results of the cruncher after the switch to the hot-qa-tiles contained `null` values for the timestamp and uid fields. Early versions of the mapbox osm-qa-tiles had the `_` as a prefix, which was changed to `@` at some point (see https://github.com/hotosm/osm-analytics-cruncher/commit/24d3c09083b300d22e94f41891892ba8df54c547), but you're right, this was indeed some time before osm-qa-tiles switched from minjur to osmium-export (https://github.com/osmlab/osm-qa-tiles/issues/24).

In the end it was just my best guess to try out to see if it helps.  :wink: It seemed to have worked, though, so maybe the new stack really does use a quite old version of minjur (or overrides the escape character to `_`?). :shrug:

PS: The "recency of edits" view of osm-analytics.org also confirms that the base OSM data represented by the hot-qa-tiles must be significantly outdated:

![image](https://user-images.githubusercontent.com/1927298/88158424-5373e700-cc0c-11ea-8550-c1055f4d465f.png)

**Comment by dakotabenjamin** [comment]
Hey folks, quick update.

It's true we were working with some outdated code, but also that we were building the qa-tiles with a planet file that was not being updated either. I have already fixed the planet file issue and am running the qa-tiles-generator process currently. 

I am also updating the generator to use `osmium export` instead of `minjur`.

**Comment by tyrasd** [comment]
> I am also updating the generator to use osmium export instead of minjur.

Can you give me a heads-up when this switch is done, so I can revert the metadata prefix change in the cruncher?

**Comment by dakotabenjamin** [comment]
@tyrasd I am going to push this tomorrow morning (us east coast): https://github.com/hotosm/hot-qa-tiles/pull/12

**Comment by tyrasd** [comment]
@dakotabenjamin thanks for the heads-up. I can't access the `hot-qa-tiles` repository though (seems to be private?). But I assume this change will just require us to change the metadata prefix back to `@`, or are there other changes involved as well?

**Comment by dakotabenjamin** [comment]
I gave you access. I also made added uncompressed planet/country tiles files which if you would like to use those instead to save some space I would recommend. In the future we may switch to only using the uncompressed tiles.

**Comment by tyrasd** [comment]
thanks. 

> I also made added uncompressed planet/country tiles files

this sounds like a good change to me. the non-gzipped planet will be available from `https://hot-qa-tiles.s3.us-east-2.amazonaws.com/latest.planet.mbtiles`, right?

**Comment by tyrasd** [comment]
> to save some space

just FYI: the cruncher has always directly unzipped the incoming data stream without saving th `.gz` to disk first (see https://github.com/hotosm/osm-analytics-cruncher/blob/master/app/run.sh#L32-L33), so if you decide to eventually phase out the`.gz` file, it would technically end up being slightly slower (and also a bit more expensive) to transfer the file to the cruncher (it seems to be about 2% bigger than the gzipped variant). But overall I think this would be almost negligible.

**Comment by tyrasd** [comment]
closing this because it is essentially full implemented and operational on the OSMA-cruncher side of things.

but @dakotabenjamin I noticed that there hasn't been a data update since the first "new" planet file published on August 22. Is everything still running fine on the hot-qa-tiles creation side? //edit: this issue was resolved in the meantime
